### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by rykovan** [lingluodlut/BioCreativeVII_DrugProt#1]
Thanks for your work! Could you please elaborate on how to prepare input data? There are values like `T18`, `T5` in https://github.com/lingluodlut/BioCreativeVII_DrugProt/blob/main/example/example_input.tsv but it is not clear how to obtain them.

**Comment by lingluodlut** [comment]
Hi,
The input data is provided by the BioCreative official organizers. They manually annotated the gene and chemical entities in documents. Or I think you can first use some NER tools (such as PubTator https://www.ncbi.nlm.nih.gov/research/pubtator/) to obtain gene and chemical entities for input data.

**Comment by rykovan** [comment]
Thanks for the prompt reply! I've made a simple snippet to convert PubTator data to format expected by `DrugProt_Tagging_PD`. Maybe it will be useful for someone else:
```python
from bioc import biocxml

pmid = 16324695
with open("biocxml.xml", 'r') as fp:
    collection = biocxml.load(fp)

doc = collection.documents[0]

text = " ".join(map(lambda x: getattr(x, "text"), doc.passages))

print(text)
for p in doc.passages:
    for a in p.annotations:
        if a.infons["type"] not in ("Gene", "Chemical"):
            continue

        etype = a.infons["type"].upper()
        start = a.locations[0].offset
        end = a.locations[0].offset + a.locations[0].length
        print(f"{pmid}\tT{a.id}\t{etype}\t{start}\t{end}\t{a.text}")
```
